### ISSUE TITLE
unregistered users cannot be added as staff members

### ISSUE THREAD

**Issue by VetGeo** [OliverDolan/VetGeo-Main#22]
currently unregistered users cannot be added as staff members

this bug will be fixed asap

the current work around is to have the staff member register with the system and then add them to your practice/clinic

**Comment by Elric74** [comment]
The same problem , on delete/update email  staff member who not validate

**Comment by OliverDolan** [comment]
Hi @Elric74 can you explain how to reproduce the issue and I can prioritize to fix it. Thanks Oliver

**Comment by OliverDolan** [comment]
This is now working as expected, issue can be closed
