### ISSUE TITLE
Problom

### ISSUE THREAD

**Issue by mako1596** [OliverDolan/VetGeo-Main#48]
The contacts I can only add one and if I try to add another it says cant be created.

**Comment by OliverDolan** [comment]
Hi thanks for getting in contact with us, are you entering email addresses for both contacts? Are they the same?

**Comment by mako1596** [comment]
no I am not entering emails.

**Comment by OliverDolan** [comment]
Hi i spotted the issue and have resolved it thanks for reporting it
